#!/usr/bin/env bash
# Using: https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#install-recipes
# and following the Ubuntu path.
#
sudo add-apt-repository ppa:neovim-ppa/unstable -y
sudo apt update
sudo apt install make gcc ripgrep unzip git xclip neovim

# I have a fork of the kickstart repo, so I'll use that.
# https://github.com/searjeant/kickstart.nvim

# This will overwrite whatever's already installed. 
git clone https://github.com/searjeant/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim

